description: 'Configure the AI MCP Oauth2 plugin'

title: 'Configure the AI MCP Oauth2 plugin'

weight: 900

config:
  resource: ${mcp_auth_url}
  authorization_servers:
    - ${keycloak_authz_url}
  introspection_endpoint: ${keycloak_introspection_url}
  client_id: ${client_id}
  client_secret: ${client_secret}
  claim_to_header:
    - claim: "sub"
      header: "X-User-Id"

variables:
  mcp_auth_url:
    value: $MCP_AUTH_URL
    description: The MCP authentication resource endpoint.
  keycloak_authz_url:
    value: $KEYCLOAK_AUTHZ_URL
    description: The Keycloak authorization server URL.
  keycloak_introspection_url:
    value: $KEYCLOAK_INTROSPECTION_URL
    description: The Keycloak token introspection endpoint.
  client_id:
    value: $CLIENT_ID
    description: The client ID for the OIDC client.
  client_secret:
    value: $CLIENT_SECRET
    description: The client secret for the OIDC client.


min_version:
  gateway: '3.12'

tools:
  - deck
  - admin-api
  - konnect-api
  - kic
  - terraform