title: "OpenAI SDK: Multi-provider chat routing"
description: Use a single OpenAI SDK client to route chat requests to different LLM providers by defining separate Routes per provider.
extended_description: |
  Use a single OpenAI SDK client to route chat requests to different LLM providers by defining separate Routes per provider.

  Configure multiple chat Routes in {{site.base_gateway}}, each targeting a different LLM provider such as Cohere or Mistral,
  while using the same OpenAI-compatible SDK client. The AI Proxy plugin extracts the model name from the request path,
  and injects provider-specific credentials automatically. This lets you arbitrate between providers without changing client logic,
  using only the base URL to select a provider.

  Using this configuration, you can select your desired provider using the SDK:

  ```python
  client = OpenAI(
  base_url="http://127.0.0.1:8000/cohere"
  )
  ```
  Or:

  ```python
  client = OpenAI(
  base_url="http://127.0.0.1:8000/mistral"
  )
  ```

   {:.warning}
    > For this configuration to work properly, you need two [Routes](/gateway/entities/route/#set-up-a-route) with the following configuration:
    > ```
    > routes:
    >  - name: cohere-chat
    >    paths:
    >      - "~/cohere/(?<model>[^#?/]+)/chat/completions$"
    >    methods:
    >      - POST
    > ```
    > and:
    > ```
    > routes:
    >  - name: mistral-chat
    >    paths:
    >      - "~/mistral(?<model>[^#?/]+)/chat/completions$"
    >    methods:
    >      - POST
    > ```

weight: 106

requirements:
- Cohere account
- Mistral account

config:
  - route_type: llm/v1/chat
    auth:
      header_name: Authorization
      header_value: ${cohere_key}
    logging:
      log_statistics: true
      log_payloads: false
    model:
      provider: openai
      name: $(uri_captures.model)
  - route_type: llm/v1/chat
    auth:
      header_name: Authorization
      header_value: ${mistral_key}
    logging:
      log_statistics: true
      log_payloads: false
    model:
      provider: mistral
      name: $(uri_captures.model)

variables:
  cohere_key:
    value: $COHERE_API_KEY
    description: The API key to authenticate requests to Cohere.
  mistral_key:
    value: $MISTRAL_API_KEY
    description: The API key to authenticate requests to Mistral.


tools:
  - deck
  - admin-api
  - konnect-api
  - kic
  - terraform

group: open-ai