extends: spelling
message: "Did you really mean '%s'?"
level: error
filters:
  - '\W'
ignore:
 - .github/styles/base/Dictionary.txt
 - .github/styles/base/Auto-Ignore.txt
 - .github/styles/landing_pages/Components.txt
 - .github/styles/landing_pages/Auto-ignore.txt