name: Install deps
description: Install deps
runs:
  using: composite
  steps:
    # Configure Ruby to build Jekyll site
    - name: Set up Ruby
      uses: ruby/setup-ruby@84684c07c1965536eb4802c8daf1a77968df0cb1 # v1
      with:
        ruby-version: .ruby-version

    - name: Ruby gem cache
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      with:
        path: ${{ github.workspace }}/vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Bundle Setup
      shell: bash
      run: bundle config path ${{ github.workspace }}/vendor/bundle

    - name: Bundle Install
      shell: bash
      run: bundle install --jobs 4 --retry 3

    # Configure Node to build assets
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version: "24"

    - name: Cache node modules
      uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    - name: npm install
      shell: bash
      run: npm ci
