name: Install deps
description: Install deps
runs:
  using: composite
  steps:
    # Configure Ruby to build Jekyll site
    - name: Set up Ruby
      uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1.327.0
      with:
        ruby-version: .ruby-version

    - name: Ruby gem cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: ${{ github.workspace }}/vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Bundle Setup
      shell: bash
      run: bundle config path ${{ github.workspace }}/vendor/bundle

    - name: Bundle Install
      shell: bash
      run: bundle install --jobs 4 --retry 3

    # Configure Node to build assets
    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7
      with:
        node-version: "24"
        cache: 'yarn'

    - name: Install node packages
      shell: bash
      run: yarn install --immutable
