import fs from "fs";
import path from "path";
import { execFileSync } from "child_process";
import { fileURLToPath } from "url";
import matter from "gray-matter";
import YAML from "yaml";

const SITE_BASE_URL = "https://developer.konghq.com";
const DEFAULT_SEED_SINCE = "7 days ago";
// A backfill sweeps full history by default, but this digest only needs to
// start from 2026 — older content isn't worth surfacing retroactively.
const BACKFILL_DEFAULT_SEED_SINCE = "2026-01-01";
const OUTPUT_RELATIVE_PATH = "docs/new-pages-changelog.md";

// Only these content types are surfaced. `support` is deliberately excluded
// per user feedback. Auto-generated collections (_references, _changelogs,
// _api, kongctl/deck help) either fall outside the .md/_landing_pages glob
// below or never carry a content_type in their own frontmatter (it's
// injected by Jekyll's `defaults:` at build time, not authored in the file).
const CURATED_CONTENT_TYPES = new Set([
  "how_to",
  "landing_page",
  "concept",
  "plugin",
  "policy",
  "cookbook",
  "reference",
]);

const EXCLUDED_PATH_PREFIXES = [
  "app/_layouts/",
  "app/_includes/",
  "app/_api/",
  // Auto-generated (CLI/PDK/OAS reference pages) — no content_type in their
  // own frontmatter anyway, but kept explicit for clarity.
  "app/_references/",
  // Deliberately excluded per user feedback: some support pages (e.g. FAQs)
  // carry content_type: reference, but support content stays out of scope.
  "app/_support/",
  "app/_changelogs/",
  "app/assets/",
  "app/.repos/",
];

const DEFAULT_HEADER = `# New pages published

Internal, auto-generated changelog of newly published content pages on developer.konghq.com, grouped by week. Generated by \`tools/new-pages-changelog\` on a weekly schedule (see \`.github/workflows/new-pages-changelog.yml\`) — do not edit by hand.
`;

function run(args, cwd) {
  return execFileSync("git", args, { cwd, encoding: "utf8" }).trim();
}

function getRepoRoot() {
  return run(["rev-parse", "--show-toplevel"], process.cwd());
}

// A squash-merge (this repo's default) discards the original branch commits,
// so a marker sha recorded before a squash may no longer exist as an
// ancestor of HEAD once that PR lands — `git log <sha>..HEAD` would then
// fail with "Invalid revision range". Check first so a stale marker falls
// back to the seed window instead of crashing the whole run.
function isValidMarker(repoRoot, sha) {
  if (!sha) return false;
  try {
    execFileSync("git", ["merge-base", "--is-ancestor", sha, "HEAD"], { cwd: repoRoot, stdio: "ignore" });
    return true;
  } catch {
    return false;
  }
}

function parseArgs(argv) {
  const args = { dryRun: false, sinceSha: null, seedSince: DEFAULT_SEED_SINCE, backfillTypes: null, pruneBefore: null };
  for (const arg of argv) {
    if (arg === "--dry-run") args.dryRun = true;
    else if (arg.startsWith("--since-sha=")) args.sinceSha = arg.slice("--since-sha=".length);
    else if (arg.startsWith("--seed-since=")) args.seedSince = arg.slice("--seed-since=".length);
    else if (arg.startsWith("--backfill=")) {
      args.backfillTypes = arg
        .slice("--backfill=".length)
        .split(",")
        .map((type) => type.trim())
        .filter(Boolean);
      // Defaults to BACKFILL_DEFAULT_SEED_SINCE unless --seed-since/--since-sha
      // was also given — a content type just became curated, so its history
      // predates the marker or a "N days ago" window, but this digest still
      // doesn't need to reach back further than that floor.
      if (args.seedSince === DEFAULT_SEED_SINCE) args.seedSince = BACKFILL_DEFAULT_SEED_SINCE;
    } else if (arg.startsWith("--prune-before=")) {
      args.pruneBefore = arg.slice("--prune-before=".length);
    }
  }
  return args;
}

function readExisting(outputPath) {
  if (!fs.existsSync(outputPath)) {
    return { header: DEFAULT_HEADER, sha: null, body: "" };
  }
  const content = fs.readFileSync(outputPath, "utf8");
  const markerRegex = /<!--\s*last-processed-sha:\s*([0-9a-f]*)\s*-->/;
  const match = content.match(markerRegex);
  if (!match) {
    // No marker found (e.g. hand-edited file) — treat everything as header,
    // start with a fresh marker.
    return { header: content.trimEnd() + "\n", sha: null, body: "" };
  }
  const header = content.slice(0, match.index).trimEnd() + "\n";
  const body = content.slice(match.index + match[0].length).replace(/^\s*\n/, "");
  return { header, sha: match[1] || null, body };
}

function loadSiteVars(repoRoot) {
  const raw = fs.readFileSync(path.join(repoRoot, "jekyll.yml"), "utf8");
  const data = YAML.parse(raw);
  const vars = {};
  for (const [key, value] of Object.entries(data)) {
    if (typeof value === "string") vars[key] = value;
  }
  return vars;
}

function resolveSiteVars(str, siteVars) {
  if (typeof str !== "string") return str;
  return str.replace(/\{\{\s*site\.([a-zA-Z0-9_]+)\s*\}\}/g, (full, key) =>
    Object.prototype.hasOwnProperty.call(siteVars, key) ? siteVars[key] : full,
  );
}

function getAddedFiles(repoRoot, fromSha, seedSince) {
  const format = "COMMIT|%H|%ad";
  const gitArgs = ["log", "--no-merges", "--diff-filter=A", "--name-only", `--pretty=format:${format}`, "--date=short"];
  if (fromSha) {
    gitArgs.splice(1, 0, `${fromSha}..HEAD`);
  } else if (seedSince) {
    gitArgs.splice(1, 0, `--since=${seedSince}`);
  }
  // else: neither a from-sha nor a seed window — full unbounded history.
  gitArgs.push("--", "app");

  const output = run(gitArgs, repoRoot);
  if (!output) return [];

  const entries = [];
  let current = null;
  for (const line of output.split("\n")) {
    if (line.startsWith("COMMIT|")) {
      const [, sha, date] = line.split("|");
      current = { sha, date };
      continue;
    }
    if (!line.trim() || !current) continue;
    entries.push({ file: line.trim(), sha: current.sha, date: current.date });
  }
  return entries;
}

// Content fragments merged into a parent page, not standalone pages of
// their own — no title, no permalink. Mirrors the ignore glob already used
// in tools/frontmatter-validator/index.js.
const EXCLUDED_PATH_PATTERNS = [/^app\/_kong_plugins\/[^/]+\/reference\.md$/];

function isExcluded(file) {
  if (EXCLUDED_PATH_PREFIXES.some((prefix) => file.startsWith(prefix))) return true;
  return EXCLUDED_PATH_PATTERNS.some((pattern) => pattern.test(file));
}

function isCuratedPath(file) {
  if (isExcluded(file)) return false;
  if (file.endsWith(".md")) return true;
  if (file.startsWith("app/_landing_pages/") && /\.ya?ml$/.test(file)) return true;
  return false;
}

function loadFrontmatter(repoRoot, file) {
  const absPath = path.join(repoRoot, file);
  const raw = fs.readFileSync(absPath, "utf8");
  if (file.endsWith(".md")) {
    return matter(raw).data || {};
  }
  const parsed = YAML.parse(raw);
  return (parsed && parsed.metadata) || {};
}

// Fallback permalink derivation for pages that don't declare an explicit
// `permalink` in frontmatter. Ported from the path table already documented
// in .claude/skills/release-changelog/SKILL.md.
function derivePermalink(file) {
  let match;

  if ((match = file.match(/^app\/_how-tos\/[^/]+\/([^/]+)\.md$/))) {
    return `/how-to/${match[1]}/`;
  }
  if ((match = file.match(/^app\/_gateway_entities\/([^/]+)\.md$/))) {
    return `/gateway/entities/${match[1]}/`;
  }
  if ((match = file.match(/^app\/_ai_gateway_entities\/([^/]+)\.md$/))) {
    return `/ai-gateway/entities/${match[1]}/`;
  }
  if ((match = file.match(/^app\/_kong_plugins\/([^/]+)\/index\.md$/))) {
    return `/plugins/${match[1]}/`;
  }
  if ((match = file.match(/^app\/_kong_plugins\/([^/]+)\/examples\/([^/]+)\.md$/))) {
    return `/plugins/${match[1]}/examples/${match[2]}/`;
  }
  if ((match = file.match(/^app\/_ai_gateway_policies\/([^/]+)\/index\.md$/))) {
    // Doesn't account for policy.unreleased? (renders at .../<slug>/<min_release>/
    // instead until the policy's min_version ships) — accepted gap, see plan.
    return `/ai-gateway/policies/${match[1]}/`;
  }
  if ((match = file.match(/^app\/_landing_pages\/(.+)\.ya?ml$/))) {
    return `/${match[1]}/`;
  }
  // Ordinary pages outside a special collection (e.g. app/gateway/foo.md,
  // app/ai-gateway/foo.md) get Jekyll's default pretty permalink: the file
  // path relative to `app/`, extension stripped.
  if ((match = file.match(/^app\/(?!_)(.+)\.md$/))) {
    return `/${match[1]}/`;
  }
  return null;
}

// AI Gateway policy pages (app/_ai_gateway_policies/<slug>/index.md) have no
// frontmatter `title` — the real title is composed at render time as
// "<kong plugin title> Policy" from a Jekyll data pipeline this script can't
// easily replicate. Every policy slug maps 1:1 to a Kong Gateway plugin doc
// (app/_kong_plugins/<slug>/index.md) that already has the exact display
// name in its own `title` frontmatter, so reuse that instead of guessing.
function aiGatewayPolicyTitle(repoRoot, slug) {
  const pluginIndexPath = path.join(repoRoot, "app/_kong_plugins", slug, "index.md");
  if (fs.existsSync(pluginIndexPath)) {
    try {
      const data = matter(fs.readFileSync(pluginIndexPath, "utf8")).data || {};
      if (typeof data.title === "string" && data.title) return `${data.title} Policy`;
    } catch {
      // fall through to the slug-derived name
    }
  }

  // Fallback for the rare policy with no matching plugin doc: title-case the
  // slug, uppercasing a standalone "ai" token.
  const words = slug.split("-").map((word) => (word === "ai" ? "AI" : word.charAt(0).toUpperCase() + word.slice(1)));
  return `${words.join(" ")} Policy`;
}

const productNameCache = new Map();

function productDisplayName(repoRoot, slug) {
  if (productNameCache.has(slug)) return productNameCache.get(slug);
  const dataPath = path.join(repoRoot, "app/_data/products", `${slug}.yml`);
  let name = slug
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
  if (fs.existsSync(dataPath)) {
    try {
      const parsed = YAML.parse(fs.readFileSync(dataPath, "utf8"));
      if (parsed && typeof parsed.name === "string") name = parsed.name;
    } catch {
      // fall through to the slug-derived name
    }
  }
  productNameCache.set(slug, name);
  return name;
}

// ISO week (Monday-start) label for a YYYY-MM-DD date string.
function weekLabel(dateStr) {
  const date = new Date(`${dateStr}T00:00:00Z`);
  const day = date.getUTCDay() || 7; // Sunday -> 7
  const monday = new Date(date);
  monday.setUTCDate(date.getUTCDate() - day + 1);
  const iso = monday.toISOString().slice(0, 10);
  return { label: `Week of ${iso}`, sortKey: iso };
}

function buildEntries(repoRoot, addedFiles, siteVars) {
  const seen = new Set();
  const entries = [];

  for (const { file, date } of addedFiles) {
    if (seen.has(file)) continue;
    seen.add(file);

    if (!isCuratedPath(file)) continue;
    if (!fs.existsSync(path.join(repoRoot, file))) continue; // added then removed within the window

    let data;
    try {
      data = loadFrontmatter(repoRoot, file);
    } catch (err) {
      console.warn(`Skipping ${file}: could not parse frontmatter (${err.message})`);
      continue;
    }

    if (!data.content_type || !CURATED_CONTENT_TYPES.has(data.content_type)) continue;

    // Cookbooks use a `url` frontmatter key instead of `permalink`.
    const permalink = data.permalink || data.url || derivePermalink(file);
    if (!permalink) {
      console.warn(`Skipping ${file}: could not resolve a permalink`);
      continue;
    }

    const policySlugMatch = file.match(/^app\/_ai_gateway_policies\/([^/]+)\/index\.md$/);
    const title = policySlugMatch
      ? aiGatewayPolicyTitle(repoRoot, policySlugMatch[1])
      : resolveSiteVars(data.title, siteVars) || file;
    const products = Array.isArray(data.products) && data.products.length ? data.products : ["other"];
    const { label, sortKey } = weekLabel(date);

    entries.push({
      file,
      title,
      permalink,
      products,
      weekLabel: label,
      weekSortKey: sortKey,
      contentType: data.content_type,
    });
  }

  return entries;
}

// Parses an existing output body's "## Week of X" / "### Product" / "- [..]"
// structure into weekSortKey -> { label, products: Map<productName, string[]> }
// so a backfill can merge new entries into it without disturbing anything
// already there.
function parseWeekBlocks(body) {
  const weeks = new Map();
  let currentWeek = null;
  let currentProduct = null;

  for (const line of body.split("\n")) {
    const weekMatch = line.match(/^## Week of (\d{4}-\d{2}-\d{2})$/);
    if (weekMatch) {
      const sortKey = weekMatch[1];
      if (!weeks.has(sortKey)) weeks.set(sortKey, { label: line.slice(3), products: new Map() });
      currentWeek = weeks.get(sortKey);
      currentProduct = null;
      continue;
    }
    const productMatch = line.match(/^### (.+)$/);
    if (productMatch && currentWeek) {
      if (!currentWeek.products.has(productMatch[1])) currentWeek.products.set(productMatch[1], []);
      currentProduct = currentWeek.products.get(productMatch[1]);
      continue;
    }
    if (line.startsWith("- [") && currentProduct) {
      currentProduct.push(line);
    }
    // Any other line (blank lines, stray text outside a recognized block) is
    // dropped — the body is fully regenerated from the parsed structure.
  }

  return weeks;
}

function extractExistingPermalinks(body) {
  const permalinks = new Set();
  // Literal (not built from SITE_BASE_URL) so the dots are unambiguously
  // escaped in the source rather than via runtime string escaping.
  const regex = /\]\(https:\/\/developer\.konghq\.com([^)]*)\)/g;
  let match;
  while ((match = regex.exec(body))) permalinks.add(match[1]);
  return permalinks;
}

function mergeEntriesIntoWeeks(weeks, entries, repoRoot) {
  for (const entry of entries) {
    if (!weeks.has(entry.weekSortKey)) weeks.set(entry.weekSortKey, { label: entry.weekLabel, products: new Map() });
    const week = weeks.get(entry.weekSortKey);

    const productSlug = entry.products[0];
    const productName = productSlug === "other" ? "Other" : productDisplayName(repoRoot, productSlug);
    if (!week.products.has(productName)) week.products.set(productName, []);
    week.products.get(productName).push(`- [${entry.title}](${SITE_BASE_URL}${entry.permalink})`);
  }
}

function serializeWeeks(weeks) {
  const weekKeys = [...weeks.keys()].sort().reverse();
  const sections = [];

  for (const weekKey of weekKeys) {
    const { label, products } = weeks.get(weekKey);
    const productNames = [...products.keys()].sort();
    const lines = [`## ${label}`, ""];
    for (const productName of productNames) {
      lines.push(`### ${productName}`, "", ...products.get(productName), "");
    }
    sections.push(lines.join("\n").trimEnd());
  }

  return sections.join("\n\n");
}

function runBackfill(args, repoRoot, outputPath) {
  const existing = readExisting(outputPath);
  const addedFiles = getAddedFiles(repoRoot, args.sinceSha, args.seedSince);
  const siteVars = loadSiteVars(repoRoot);
  const entries = buildEntries(repoRoot, addedFiles, siteVars).filter((entry) =>
    args.backfillTypes.includes(entry.contentType),
  );

  const existingPermalinks = extractExistingPermalinks(existing.body);
  const newEntries = entries.filter((entry) => !existingPermalinks.has(entry.permalink));

  if (newEntries.length === 0) {
    console.log(`No new pages to backfill for content type(s): ${args.backfillTypes.join(", ")}`);
    return;
  }

  const weeks = parseWeekBlocks(existing.body);
  mergeEntriesIntoWeeks(weeks, newEntries, repoRoot);
  const newBody = `${serializeWeeks(weeks)}\n`;

  // Marker is left untouched — a backfill fills gaps behind it, it doesn't
  // move the incremental cursor forward.
  const marker = `<!-- last-processed-sha: ${existing.sha ?? ""} -->`;
  const output = `${existing.header}\n${marker}\n\n${newBody}`;

  if (args.dryRun) {
    console.log(output);
    return;
  }

  fs.writeFileSync(outputPath, output);
  console.log(`Backfilled ${newEntries.length} page(s) into ${OUTPUT_RELATIVE_PATH}`);
}

function runPrune(args, outputPath) {
  const existing = readExisting(outputPath);
  const weeks = parseWeekBlocks(existing.body);

  const before = weeks.size;
  for (const sortKey of weeks.keys()) {
    if (sortKey < args.pruneBefore) weeks.delete(sortKey);
  }
  const removed = before - weeks.size;

  if (removed === 0) {
    console.log(`No weeks before ${args.pruneBefore} found; nothing to prune.`);
    return;
  }

  const newBody = `${serializeWeeks(weeks)}\n`;
  const marker = `<!-- last-processed-sha: ${existing.sha ?? ""} -->`;
  const output = `${existing.header}\n${marker}\n\n${newBody}`;

  if (args.dryRun) {
    console.log(output);
    return;
  }

  fs.writeFileSync(outputPath, output);
  console.log(`Pruned ${removed} week(s) before ${args.pruneBefore} from ${OUTPUT_RELATIVE_PATH}`);
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const repoRoot = getRepoRoot();
  const outputPath = path.join(repoRoot, OUTPUT_RELATIVE_PATH);

  if (args.pruneBefore) {
    runPrune(args, outputPath);
    return;
  }

  if (args.backfillTypes) {
    runBackfill(args, repoRoot, outputPath);
    return;
  }

  const existing = readExisting(outputPath);
  let fromSha = args.sinceSha || existing.sha;
  let markerNeedsHealing = false;
  if (fromSha && !isValidMarker(repoRoot, fromSha)) {
    console.warn(
      `Marker ${fromSha} is not an ancestor of HEAD (likely squashed away by a merge) — falling back to --seed-since="${args.seedSince}".`,
    );
    fromSha = null;
    markerNeedsHealing = true;
  }

  const addedFiles = getAddedFiles(repoRoot, fromSha, args.seedSince);
  const siteVars = loadSiteVars(repoRoot);
  const entries = buildEntries(repoRoot, addedFiles, siteVars);

  const headSha = run(["rev-parse", "HEAD"], repoRoot);

  // Deduped by permalink against what's already recorded, not just assumed-new
  // from the sha range — a stale marker falling back to a window (or any
  // other overlap) must never produce duplicate entries.
  const existingPermalinks = extractExistingPermalinks(existing.body);
  const newEntries = entries.filter((entry) => !existingPermalinks.has(entry.permalink));

  if (newEntries.length === 0 && !markerNeedsHealing) {
    console.log("No qualifying new pages found; nothing to do.");
    return;
  }

  const weeks = parseWeekBlocks(existing.body);
  mergeEntriesIntoWeeks(weeks, newEntries, repoRoot);
  const body = `${serializeWeeks(weeks)}\n`;
  const marker = `<!-- last-processed-sha: ${headSha} -->`;
  const output = `${existing.header}\n${marker}\n\n${body}`;

  if (args.dryRun) {
    console.log(output);
    return;
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, output);
  if (newEntries.length > 0) {
    console.log(`Wrote ${newEntries.length} new page(s) to ${OUTPUT_RELATIVE_PATH}`);
  } else {
    console.log(`Healed stale marker in ${OUTPUT_RELATIVE_PATH} (no new pages to add).`);
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}
