import fs from "fs";
import path from "path";
import { execFileSync } from "child_process";
import { fileURLToPath } from "url";
import matter from "gray-matter";
import YAML from "yaml";

const SITE_BASE_URL = "https://developer.konghq.com";
const DEFAULT_SEED_SINCE = "7 days ago";
const OUTPUT_RELATIVE_PATH = "docs/new-pages-changelog.md";

// Only these content types are surfaced. Auto-generated collections
// (_references, _changelogs, _api, kongctl/deck help) either fall outside
// the .md/_landing_pages glob below or never carry one of these values.
const CURATED_CONTENT_TYPES = new Set([
  "how_to",
  "landing_page",
  "concept",
  "plugin",
  "policy",
  "cookbook",
]);

const EXCLUDED_PATH_PREFIXES = [
  "app/_layouts/",
  "app/_includes/",
  "app/_api/",
  "app/_references/",
  "app/_changelogs/",
  "app/assets/",
  "app/.repos/",
];

const DEFAULT_HEADER = `# New pages published

Internal, auto-generated changelog of newly published content pages on developer.konghq.com, grouped by week. Generated by \`tools/new-pages-changelog\` on a weekly schedule (see \`.github/workflows/new-pages-changelog.yml\`) — do not edit by hand.
`;

function run(args, cwd) {
  return execFileSync("git", args, { cwd, encoding: "utf8" }).trim();
}

function getRepoRoot() {
  return run(["rev-parse", "--show-toplevel"], process.cwd());
}

function parseArgs(argv) {
  const args = { dryRun: false, sinceSha: null, seedSince: DEFAULT_SEED_SINCE };
  for (const arg of argv) {
    if (arg === "--dry-run") args.dryRun = true;
    else if (arg.startsWith("--since-sha=")) args.sinceSha = arg.slice("--since-sha=".length);
    else if (arg.startsWith("--seed-since=")) args.seedSince = arg.slice("--seed-since=".length);
  }
  return args;
}

function readExisting(outputPath) {
  if (!fs.existsSync(outputPath)) {
    return { header: DEFAULT_HEADER, sha: null, body: "" };
  }
  const content = fs.readFileSync(outputPath, "utf8");
  const markerRegex = /<!--\s*last-processed-sha:\s*([0-9a-f]*)\s*-->/;
  const match = content.match(markerRegex);
  if (!match) {
    // No marker found (e.g. hand-edited file) — treat everything as header,
    // start with a fresh marker.
    return { header: content.trimEnd() + "\n", sha: null, body: "" };
  }
  const header = content.slice(0, match.index).trimEnd() + "\n";
  const body = content.slice(match.index + match[0].length).replace(/^\s*\n/, "");
  return { header, sha: match[1] || null, body };
}

function loadSiteVars(repoRoot) {
  const raw = fs.readFileSync(path.join(repoRoot, "jekyll.yml"), "utf8");
  const data = YAML.parse(raw);
  const vars = {};
  for (const [key, value] of Object.entries(data)) {
    if (typeof value === "string") vars[key] = value;
  }
  return vars;
}

function resolveSiteVars(str, siteVars) {
  if (typeof str !== "string") return str;
  return str.replace(/\{\{\s*site\.([a-zA-Z0-9_]+)\s*\}\}/g, (full, key) =>
    Object.prototype.hasOwnProperty.call(siteVars, key) ? siteVars[key] : full,
  );
}

function getAddedFiles(repoRoot, fromSha, seedSince) {
  const format = "COMMIT|%H|%ad";
  const gitArgs = ["log", "--no-merges", "--diff-filter=A", "--name-only", `--pretty=format:${format}`, "--date=short"];
  if (fromSha) {
    gitArgs.splice(1, 0, `${fromSha}..HEAD`);
  } else {
    gitArgs.splice(1, 0, `--since=${seedSince}`);
  }
  gitArgs.push("--", "app");

  const output = run(gitArgs, repoRoot);
  if (!output) return [];

  const entries = [];
  let current = null;
  for (const line of output.split("\n")) {
    if (line.startsWith("COMMIT|")) {
      const [, sha, date] = line.split("|");
      current = { sha, date };
      continue;
    }
    if (!line.trim() || !current) continue;
    entries.push({ file: line.trim(), sha: current.sha, date: current.date });
  }
  return entries;
}

function isExcluded(file) {
  return EXCLUDED_PATH_PREFIXES.some((prefix) => file.startsWith(prefix));
}

function isCuratedPath(file) {
  if (isExcluded(file)) return false;
  if (file.endsWith(".md")) return true;
  if (file.startsWith("app/_landing_pages/") && /\.ya?ml$/.test(file)) return true;
  return false;
}

function loadFrontmatter(repoRoot, file) {
  const absPath = path.join(repoRoot, file);
  const raw = fs.readFileSync(absPath, "utf8");
  if (file.endsWith(".md")) {
    return matter(raw).data || {};
  }
  const parsed = YAML.parse(raw);
  return (parsed && parsed.metadata) || {};
}

// Fallback permalink derivation for pages that don't declare an explicit
// `permalink` in frontmatter. Ported from the path table already documented
// in .claude/skills/release-changelog/SKILL.md.
function derivePermalink(file) {
  let match;

  if ((match = file.match(/^app\/_how-tos\/[^/]+\/([^/]+)\.md$/))) {
    return `/how-to/${match[1]}/`;
  }
  if ((match = file.match(/^app\/_gateway_entities\/([^/]+)\.md$/))) {
    return `/gateway/entities/${match[1]}/`;
  }
  if ((match = file.match(/^app\/_ai_gateway_entities\/([^/]+)\.md$/))) {
    return `/ai-gateway/entities/${match[1]}/`;
  }
  if ((match = file.match(/^app\/_kong_plugins\/([^/]+)\/index\.md$/))) {
    return `/plugins/${match[1]}/`;
  }
  if ((match = file.match(/^app\/_kong_plugins\/([^/]+)\/examples\/([^/]+)\.md$/))) {
    return `/plugins/${match[1]}/examples/${match[2]}/`;
  }
  if ((match = file.match(/^app\/_ai_gateway_policies\/([^/]+)\/index\.md$/))) {
    // Doesn't account for policy.unreleased? (renders at .../<slug>/<min_release>/
    // instead until the policy's min_version ships) — accepted gap, see plan.
    return `/ai-gateway/policies/${match[1]}/`;
  }
  if ((match = file.match(/^app\/_landing_pages\/(.+)\.ya?ml$/))) {
    return `/${match[1]}/`;
  }
  // Ordinary pages outside a special collection (e.g. app/gateway/foo.md,
  // app/ai-gateway/foo.md) get Jekyll's default pretty permalink: the file
  // path relative to `app/`, extension stripped.
  if ((match = file.match(/^app\/(?!_)(.+)\.md$/))) {
    return `/${match[1]}/`;
  }
  return null;
}

// AI Gateway policy pages (app/_ai_gateway_policies/<slug>/index.md) have no
// frontmatter `title` — the real title is composed at render time as
// "<kong plugin title> Policy" from a Jekyll data pipeline this script can't
// easily replicate. Every policy slug maps 1:1 to a Kong Gateway plugin doc
// (app/_kong_plugins/<slug>/index.md) that already has the exact display
// name in its own `title` frontmatter, so reuse that instead of guessing.
function aiGatewayPolicyTitle(repoRoot, slug) {
  const pluginIndexPath = path.join(repoRoot, "app/_kong_plugins", slug, "index.md");
  if (fs.existsSync(pluginIndexPath)) {
    try {
      const data = matter(fs.readFileSync(pluginIndexPath, "utf8")).data || {};
      if (typeof data.title === "string" && data.title) return `${data.title} Policy`;
    } catch {
      // fall through to the slug-derived name
    }
  }

  // Fallback for the rare policy with no matching plugin doc: title-case the
  // slug, uppercasing a standalone "ai" token.
  const words = slug.split("-").map((word) => (word === "ai" ? "AI" : word.charAt(0).toUpperCase() + word.slice(1)));
  return `${words.join(" ")} Policy`;
}

const productNameCache = new Map();

function productDisplayName(repoRoot, slug) {
  if (productNameCache.has(slug)) return productNameCache.get(slug);
  const dataPath = path.join(repoRoot, "app/_data/products", `${slug}.yml`);
  let name = slug
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
  if (fs.existsSync(dataPath)) {
    try {
      const parsed = YAML.parse(fs.readFileSync(dataPath, "utf8"));
      if (parsed && typeof parsed.name === "string") name = parsed.name;
    } catch {
      // fall through to the slug-derived name
    }
  }
  productNameCache.set(slug, name);
  return name;
}

// ISO week (Monday-start) label for a YYYY-MM-DD date string.
function weekLabel(dateStr) {
  const date = new Date(`${dateStr}T00:00:00Z`);
  const day = date.getUTCDay() || 7; // Sunday -> 7
  const monday = new Date(date);
  monday.setUTCDate(date.getUTCDate() - day + 1);
  const iso = monday.toISOString().slice(0, 10);
  return { label: `Week of ${iso}`, sortKey: iso };
}

function buildEntries(repoRoot, addedFiles, siteVars) {
  const seen = new Set();
  const entries = [];

  for (const { file, date } of addedFiles) {
    if (seen.has(file)) continue;
    seen.add(file);

    if (!isCuratedPath(file)) continue;
    if (!fs.existsSync(path.join(repoRoot, file))) continue; // added then removed within the window

    let data;
    try {
      data = loadFrontmatter(repoRoot, file);
    } catch (err) {
      console.warn(`Skipping ${file}: could not parse frontmatter (${err.message})`);
      continue;
    }

    if (!data.content_type || !CURATED_CONTENT_TYPES.has(data.content_type)) continue;

    const permalink = data.permalink || derivePermalink(file);
    if (!permalink) {
      console.warn(`Skipping ${file}: could not resolve a permalink`);
      continue;
    }

    const policySlugMatch = file.match(/^app\/_ai_gateway_policies\/([^/]+)\/index\.md$/);
    const title = policySlugMatch
      ? aiGatewayPolicyTitle(repoRoot, policySlugMatch[1])
      : resolveSiteVars(data.title, siteVars) || file;
    const products = Array.isArray(data.products) && data.products.length ? data.products : ["other"];
    const { label, sortKey } = weekLabel(date);

    entries.push({ file, title, permalink, products, weekLabel: label, weekSortKey: sortKey });
  }

  return entries;
}

function renderSection(entries, repoRoot) {
  const byWeek = new Map();
  for (const entry of entries) {
    if (!byWeek.has(entry.weekSortKey)) byWeek.set(entry.weekSortKey, { label: entry.weekLabel, pages: [] });
    byWeek.get(entry.weekSortKey).pages.push(entry);
  }

  const weekKeys = [...byWeek.keys()].sort().reverse();
  const sections = [];

  for (const weekKey of weekKeys) {
    const { label, pages } = byWeek.get(weekKey);
    const byProduct = new Map();
    for (const page of pages) {
      // Group under the page's first listed product.
      const productSlug = page.products[0];
      const productName = productSlug === "other" ? "Other" : productDisplayName(repoRoot, productSlug);
      if (!byProduct.has(productName)) byProduct.set(productName, []);
      byProduct.get(productName).push(page);
    }

    const productNames = [...byProduct.keys()].sort();
    const lines = [`## ${label}`, ""];
    for (const productName of productNames) {
      lines.push(`### ${productName}`, "");
      for (const page of byProduct.get(productName)) {
        lines.push(`- [${page.title}](${SITE_BASE_URL}${page.permalink})`);
      }
      lines.push("");
    }
    sections.push(lines.join("\n").trimEnd());
  }

  return sections.join("\n\n");
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const repoRoot = getRepoRoot();
  const outputPath = path.join(repoRoot, OUTPUT_RELATIVE_PATH);

  const existing = readExisting(outputPath);
  const fromSha = args.sinceSha || existing.sha;

  const addedFiles = getAddedFiles(repoRoot, fromSha, args.seedSince);
  const siteVars = loadSiteVars(repoRoot);
  const entries = buildEntries(repoRoot, addedFiles, siteVars);

  const headSha = run(["rev-parse", "HEAD"], repoRoot);

  if (entries.length === 0) {
    console.log("No qualifying new pages found; nothing to do.");
    return;
  }

  const newSection = renderSection(entries, repoRoot);
  const marker = `<!-- last-processed-sha: ${headSha} -->`;
  const body = existing.body ? `${newSection}\n\n${existing.body.trimEnd()}\n` : `${newSection}\n`;
  const output = `${existing.header}\n${marker}\n\n${body}`;

  if (args.dryRun) {
    console.log(output);
    return;
  }

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, output);
  console.log(`Wrote ${entries.length} new page(s) to ${OUTPUT_RELATIVE_PATH}`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}
