extends: existence
message: "Use relative URLs for docs URLs. For example, use [Get Started](/gateway/latest/get-started/) instead of [Get Started](https://developer.konghq.com/gateway/3.3.x/get-started/). If a direct URL is necessary, use {{ site.links.web }} instead of `https://developer.konghq.com`."
nonword: true
level: error
scope: raw
tokens:
  - '\[[^\]]*\]\(https?:\/\/developer\.konghq\.com[^\)]*\)'