description: |
  Configure the plugin to connect to a Solace broker using basic authentication, 
  and send messages to multiple queues with persistent delivery. 
  
extended_description: |
  Configure the plugin to connect to a Solace broker using basic authentication, 
  and send messages to multiple queues with persistent delivery. 
  This example uses a statically configured message and includes a Lua function to
  transform message content before sending (in this case the message that the plugin
  will send is "HELLO").

title: 'Send message to Solace queues with persistent delivery'

weight: 900

variables:
  host:
    description: 'The [IPv4 or IPv6 address or hostname](https://docs.solace.com/API-Developer-Online-Ref-Documentation/c/index.html#host-entry) of the Solace broker to connect to.'
    value: tcp://127.0.0.1:55555
  username:
    description: 'The username used with `BASIC` authentication scheme when connecting to an event broker.'
    value: admin
  password:
    description: 'The password used with `BASIC` authentication scheme when connecting to an event broker.'
    value: admin
  queue1:
    description: 'The name of the first destination queue.'
    value: test
  queue2:
    description: 'The name of the second destination queue.'
    value: test2

config:
  session:
    host: ${host}
    vpn_name: default
    authentication:
      scheme: BASIC
      username: ${username}
      password: ${password}
  message:
    destinations:
      - name: ${queue1}
        type: QUEUE
      - name: ${queue2}
        type: QUEUE
    delivery_mode: PERSISTENT
    default_content: hello
    functions:
      - "return string.upper(message)"

tools:
  - deck
  - admin-api
