metadata:
  title: Security at Insomnia
rows:
  - header:
      type: h1
      text: "Security at Insomnia"
    columns:
      - blocks:
          - type: structured_text
            config:
              header: 
                text: "Learn how Insomnia prioritizes data protection through encryption, product and application security, and organizational measures."
              blocks:
                - type: text
                  text: | 
                    intro text
  - header:
      type: h2
      text: "Data security"
  - header:
      type: h2
      text: "Key security features"
  - header:
      type: h2
      text: "Infrastructure security"
  - header:
      type: h2
      text: "Physical and environmental security"
  - header:
      type: h2
      text: "Software security"
  - header:
      type: h2
      text: "Payment processing"
  - header:
      type: h2
      text: "Vulnerability management"
  - header:
      type: h2
      text: "Attack prevention and mitigation"
  - header:
      type: h2
      text: "Incident response"
  - header:
      type: h2
      text: "Shared responsibility model (user best-practices)"
  - header:
      text: "Frequently Asked Questions"
      type: h2
    columns:
      - blocks:
        - type: faqs
          config:
            - q: Does Insomnia have any compliance certifications?
              a: Not at the moment.
            


      