metadata:
  title: Security at Insomnia
  description: "Learn how Insomnia prioritizes data protection through encryption, product and application security, and organizational measures."
  breadcrumbs:
    - /insomnia/
  tags:
    - security
rows:
  - header:
      type: h1
      text: "Security at Insomnia"
      sub_text: "Learn how Insomnia prioritizes data protection through encryption, product and application security, and organizational measures."
  
  - columns:
      - blocks:
          - type: structured_text
            config:
              blocks:
                - type: text
                  text: | 
                    Insomnia believes that it is your right to know how your sensitive project data is transported and handled. 
                    The sections on this page explain how Insomnia secures data and infrastructure, what data is collected, how Insomnia responds to security incidents, and how you can increase security with Insomnia's features.
  
  - header:
      type: h2
      text: "Additional security features you can configure"
    columns:
      - blocks:
        - type: card
          config:
            title: Enterprise single sign-on (SSO)
            description: Learn about SSO security and see the different identity providers (IdPs) you can use to configure SSO.
            icon:  /assets/icons/insomnia/sso.svg
            cta:
              text: Learn more
              url: /insomnia/sso
              align: end
      - blocks:
        - type: card
          config:
            title: Local vault storage
            description: Local vault is a secure storage option that allows all project data to be stored locally on your device. This option is ideal for users and organizations who prefer or require their data to remain off the cloud for privacy or security reasons.
            icon:  /assets/icons/vault.svg
            cta:
              text: Learn more
              url: /insomnia/local-vault
              align: end
  
  - header:
      type: h2
      text: "Learn more about how Insomnia secures data"
    columns:
      - blocks:
        - type: card
          config:
            title: Data security
            description: Learn about how Insomnia data is encrypted and what data models, keys, and salts are used
            icon:  /assets/icons/insomnia/data-security.svg
            cta:
              text: Learn more
              url: /insomnia/data-security
              align: end
      - blocks:
        - type: card
          config:
            title: Infrastructure security
            description: Learn about what infrastructure security Insomnia uses
            icon: /assets/icons/insomnia/infrastructure-security.svg
            cta:
              text: Learn more
              url: /insomnia/infrastructure-security
              align: end
      - blocks:
        - type: card
          config:
            title: Collected data
            description: Learn about what data Insomnia collects and how to opt out of data collection
            icon: /assets/icons/insomnia/data-collected.svg
            cta:
              text: Learn more
              url: /insomnia/collected-data
              align: end
      - blocks:
        - type: card
          config:
            title: Incident response and vulnerability management
            description: Learn about how Insomnia reports incidents and how they manage security vulnerabilities
            icon: /assets/icons/insomnia/incident-response.svg
            cta:
              text: Learn more
              url: /insomnia/incident-response
              align: end