# api pages
app/_api/gateway/admin-ee/_index.md:
 - app/_api/gateway/admin-ee/_index.md
app/_api/gateway/admin-oss/_index.md:
 - app/_api/gateway/admin-oss/_index.md
app/_api/gateway/dev-portal/_index.md:
 - app/_api/dev-portal/_index.md
app/_api/gateway/status/_index.md:
 - app/_api/gateway/status/_index.md
app/_api/konnect/api-products/_index.md:
 - app/_api/konnect/api-products/_index.md
app/_api/konnect/analytics-requests/_index.md:
 - app/_api/konnect/api-requests/_index.md
app/_api/konnect/application-auth-strategies/_index.md:
 - app/_api/konnect/application-auth-strategies/_index.md
app/_api/konnect/audit-logs/_index.md:
 - app/_api/konnect/audit-logs/_index.md
app/_api/konnect/cloud-gateways/_index.md:
 - app/_api/konnect/cloud-gateways/_index.md
app/_api/konnect/control-planes-config/_index.md:
 - app/_api/konnect/control-plane-configuration/_index.md
app/_api/konnect/control-planes/_index.md:
 - app/_api/konnect/control-planes/_index.md
app/_api/konnect/dev-portal/_index.md:
 - app/_api/konnect-portal/_index.md
app/_api/konnect/identity/_index.md:
 - app/_api/konnect/identity-management/_index.md
app/_api/konnect/mesh-control-planes/_index.md:
 - app/_api/konnect/mesh-manager/_index.md
app/_api/konnect/portal-management/_index.md:
 - app/_api/konnect/portal-management/_index.md
app/_api/konnect/ksearch/_index.md:
 - app/_api/konnect/search/_index.md

# entities
app/_gateway_entities/consumer_group.md:
  - app/_src/gateway/key-concepts/consumer-groups.md
app/_gateway_entities/consumer.md:
  - app/_src/gateway/key-concepts/consumers.md
app/_gateway_entities/plugin.md:
  - app/hub/plugins/overview/index.md
  - app/hub/plugins/compatibility/index.md
app/_gateway_entities/route.md:
  - app/_src/gateway/key-concepts/routes.md
  - app/_src/gateway/how-kong-works/routing-traffic.md
app/_gateway_entities/service.md:
  - app/_src/gateway/key-concepts/services.md
app/_gateway_entities/target.md:
  - app/_src/gateway/key-concepts/services.md
  - app/_src/gateway/get-started/load-balancing.md
  - app/_src/gateway/key-concepts/upstreams.md
  - app/_src/gateway/how-kong-works/load-balancing.md
app/_gateway_entities/upstream.md:
  - app/_src/gateway/key-concepts/upstreams.md
  - app/_src/gateway/how-kong-works/load-balancing.md
  - app/_src/gateway/how-kong-works/health-checks.md
app/_gateway_entities/workspace.md:
  - app/_src/gateway/kong-manager/workspaces.md
  - app/_src/gateway/kong-enterprise/workspaces.md
app/_gateway_entities/route.md:
  - app/_src/gateway/how-kong-works/routing-traffic.md
  - app/_src/gateway/key-concepts/routes/index.md
app/_gateway_entities/upstream.md:
  - app/_src/gateway/key-concepts/upstreams.md
app/_gateway_entities/event_hooks.md:
  - app/_src/gateway/latest/kong-enterprise/event-hooks.md
app/_gateway_entities/rbac.md:
  - app/_src/gateway/production/access-control/enable-rbac.md
  - app/_src/gateway/production/access-control/start-securely.md
  - app/_src/gateway/production/access-control/register-admin-api.md
  - app/_src/gateway/kong-manager/auth/rbac.md
  - app/konnect/dev-portal/access-and-approval/manage-teams.md
app/_gateway_entities/group.md:
  - app/_src/gateway/kong-manager/auth/ldap/service-directory-mapping/

app/_gateway_entities/vault.md:
  - app/_src/gateway/kong-enterprise/secrets-management/advanced-usage.md
  - app/_src/deck/guides/vaults.md
  - app/_src/gateway/kong-enterprise/secrets-management/index.md
  - app/_src/gateway/kong-enterprise/secrets-management/backends/env.md
app/_gateway_entities/sni.md:
  - app/_src/gateway/how-kong-works/routing-traffic.md
app/_gateway/entities/certificate.md:
  - app/_src/gateway/how-kong-works/routing-traffic.md
app/_gateway_entities/route.md:
  - app/_src/gateway/how-kong-works/routing-traffic.md

app/_gateway_entities/license.md:
  - app/_src/gateway/licenses/index.md
  - app/_src/gateway/licenses/download.md
  - app/_src/gateway/licenses/deploy.md
  - app/_includes/md/enterprise/deploy-license.md
  - app/_src/gateway/install/docker/index.md
  - app/_src/gateway/licenses/report-v2.md
  - app/_src/gateway/licenses/examples.md

app/_gateway_entities/keyring.md:
  - app/_src/gateway/kong-enterprise/db-encryption.md
app/_how-tos/encrypt-sensitive-data-in-kong-gateway-with-keyring.md:
  - app/_src/gateway/kong-enterprise/db-encryption.md
app/_how-tos/store-keyring-in-hashicorp-vault.md:
  - app/_src/gateway/kong-enterprise/db-encryption.md
app/_gateway_entities/key.md:
  - app/_src/gateway/reference/key-management.md
app/_gateway_entities/key-set.md:
  - app/_src/gateway/reference/key-management.md
app/_how-tos/create-a-key-set-with-a-jwk.md:
  - app/_src/gateway/reference/key-management.md
app/_how-tos/create-a-key-set-with-a-pem-key.md:
  - app/_src/gateway/reference/key-management.md
app/_how-tos/create-a-super-admin.md:
  - app/_src/gateway/kong-manager/auth/super-admin.md
  - app/_src/gateway/latest/production/access-control/enable-rbac.md

app/_gateway_entities/admin.md:
  - app/_src/gateway/production/access-control/start-securely.md
  - app/_src/gateway/production/access-control/register-admin-api.md
  - app/_src/gateway/production/access-control/enable-rbac.md


# how-tos
## gateway
app/_how-tos/add-rate-limiting-tiers-with-kong-gateway.md: 
  - /app/_hub/kong-inc/rate-limiting-advanced/how-to/_index.md
app/_how-tos/custom-deck-object-defaults.md:
  - app/_src/deck/guides/defaults.md
app/_how-tos/multiple-rate-limits-window-sizes.md:
  - app/_hub/kong-inc/rate-limiting-advanced/overview/_index.md
app/_how-tos/get-started-with-gateway.md:
  - app/_src/gateway/get-started/index.md
  - app/_src/gateway/get-started/services-and-routes.md
  - app/_src/gateway/get-started/rate-limiting.md
  - app/_src/gateway/get-started/proxy-caching.md
  - app/_src/gateway/get-started/key-authentication.md
  - app/_src/gateway/get-started/load-balancing.md
app/_how-tos/set-up-ai-proxy-advanced-with-anthropic.md:
  - app/_hub/kong-inc/ai-proxy-advanced/how-to/llm-provider-integration-guides/_anthropic.md
app/_how-tos/set-up-ai-proxy-with-anthropic.md:
  - app/_hub/kong-inc/ai-proxy/how-to/llm-provider-integration-guides/_anthropic.md
app/_how-tos/proxy-tls-passthrough-traffic-using-sni.md:
  - app/_src/gateway/how-kong-works/routing-traffic.md
app/_how-tos/configure-google-cloud-secret-as-a-vault-backend.md:
  - app/_src/gateway/kong-enterprise/secrets-management/backends/gcp-sm.md
app/_how-tos/configure-azure-key-vaults-as-a-vault-backend-with-vault-entity.md:
  - app/_src/gateway/kong-enterprise/secrets-management/backends/azure-key-vaults.md
app/_how-tos/configure-aws-secrets-manager-as-a-vault-backend-with-vault-entity.md:
  - app/_src/gateway/kong-enterprise/secrets-management/backends/aws-sm.md
app/_how-tos/enable-rbac-with-admin-api.md:
  - app/_src/gateway/production/access-control/enable-rbac.md
  - app/_src/gateway/production/access-control/start-securely.md
  - app/_src/gateway/production/access-control/register-admin-api.md
  - app/_src/gateway/kong-manager/auth/rbac.md
  - app/konnect/dev-portal/access-and-approval/manage-teams.md
app/_how-tos/store-secrets-in-konnect-config-store.md:
  - app/konnect/gateway-manager/configuration/config-store.md
app/_how-tos/store-the-gateway-database-credentials-with-aws-secrets-manager.md:
  - app/_src/gateway/kong-enterprise/secrets-management/how-to/aws-secrets-manager.md
app/_how-tos/configure-hashicorp-vault-as-a-vault-backend.md:
  - app/_src/gateway/kong-enterprise/secrets-management/backends/hashicorp-vault.md
app/_how-tos/configure-the-konnect-config-store.md:
  - app/konnect/gateway-manager/configuration/config-store.md
app/_how-tos/verify-signatures-for-signed-images.md:
  - app/_src/gateway/kong-enterprise/signed-images.md
app/_how-tos/verify-build-provenance-for-signed-images.md:
  - app/_src/gateway/kong-enterprise/provenance-verification.md
app/_how-tos/proxy-tls-passthrough.md: 
  - app/_src/gateway/how-kong-works/routing-traffic.md
app/_how-tos/configure-fallback-route.md:
  - app/_src/gateway/how-kong-works/routing-traffic/
app/_how-tos/throttle-apis-with-services-and-consumers.md:
  - app/_hub/kong-inc/service-protection/how-to/_index.md
app/_how-tos/test-certificate-generation-locally-with-ngrok-and-acme.md:
  - app/_hub/kong-inc/acme/how-to/_index.md
  - app/_hub/kong-inc/acme/how-to/_local-testing-development.md
app/_how-tos/allow-multiple-authentication.md:
  - app/_src/gateway/kong-plugins/authentication/allowing-multiple-authentication-methods.md
app/_how-tos/validate-incoming-json-request-bodies.md:
  - app/_hub/kong-inc/json-threat-protection/overview/_index.md

## KIC
app/_how-tos/proxy-http-traffic-kic.md:
  - app/_src/kubernetes-ingress-controller/guides/services/http.md

# plugins
app/_kong_plugins/ai-rate-limiting-advanced/index.md:
  - app/_hub/kong-inc/ai-rate-limiting-advanced/overview/_index.md
app/_kong_plugins/basic-auth/index.md:
  - app/_hub/kong-inc/basic-auth/overview/_index.md
  - app/_hub/kong-inc/basic-auth/_changelog.md
  - app/_src/gateway/kong-plugins/authentication/reference.md
app/_kong_plugins/graphql-rate-limiting-advanced/index.md:
  - app/_hub/kong-inc/graphql-rate-limiting-advanced/overview/_index.md
app/_kong_plugins/jwt/index.md:
  - app/_hub/kong-inc/jwt/_index.md
app/_kong_plugins/key-auth/index.md:
  - app/_hub/kong-inc/key-auth/overview/_index.md
app/_kong_plugins/rate-limiting/index.md:
  - app/_hub/kong-inc/rate-limiting/overview/_index.md
app/_kong_plugins/rate-limiting-advanced/index.md:
  - app/_hub/kong-inc/rate-limiting-advanced/overview/_index.md
app/_kong_plugins/ai-proxy-advanced/index.md:
  - app/_hub/kong-inc/ai-proxy-advanced/overview/_index.md
app/_kong_plugins/ai-proxy/index.md:
  - app/_hub/kong-inc/ai-proxy/overview/_index.md
app/_kong_plugins/cors/index.md:
  - app/_hub/kong-inc/cors/overview/_index.md
app/_kong_plugins/mocking/index.md:
  - /app/_hub/kong-inc/mocking/overview/_index.md
app/_kong_plugins/injection-protection/index.md:
  - app/_hub/kong-inc/injection-protection/overview/_index.md
app/_kong_plugins/openid-connect/index.md:
  - app/_hub/kong-inc/openid-connect/overview/_index.md
  - app/_hub/kong-inc/openid-connect/overview/_primary-config-params.md
  - app/_hub/kong-inc/openid-connect/overview/_support.md
app/_kong_plugins/openid-connect/changelog.md:
  - app/_hub/kong-inc/openid-connect/_changelog.md
app/_kong_plugins/bot-detection/index.md:
  - app/_hub/kong-inc/bot-detection/overview/_index.md
app/_kong_plugins/acme/index.md:
  - app/_hub/kong-inc/acme/overview/_index.md
app/_kong_plugins/acme/changelog.md:
  - app/_hub/kong-inc/acme/_changelog.md
app/_kong_plugins/acme/examples/redis.yaml:
  - app/_hub/kong-inc/acme/how-to/_redis.md
app/_kong_plugins/service-protection/index.md:
  - app/_hub/kong-inc/service-protection/overview/_index.md
app/_kong_plugins/json-threat-protection/index.md:
  - app/_hub/kong-inc/json-threat-protection/overview/_index.md
app/_kong_plugins/json-threat-protection/changelog.md:
  - app/_hub/kong-inc/json-threat-protection/_changelog.md
app/_how-tos/block-unauthorized-requests-with-opa.md:
  - app/_hub/kong-inc/opa/overview/_index.md
app/_kong_plugins/opa/index.md:
  - app/_hub/kong-inc/opa/overview/_index.md
app/_kong_plugins/tls-metadata-headers/changelog.md:
  - app/_hub/kong-inc/tls-metadata-headers/_changelog.md
app/_kong_plugins/tls-metadata-headers/index.md:
  - app/_hub/kong-inc/tls-metadata-headers/overview/_index.md
app/_kong_plugins/ip-restriction/index.md:
  - app/_hub/kong-inc/ip-restriction/overview/_index.md
app/_kong_plugins/ip-restriction/changelog.md:
  - app/_hub/kong-inc/ip-restriction/_changelog.md
app/_kong_plugins/acl/index.md:
  - app/_hub/kong-inc/acl/how-to/_index.md
  - app/_hub/kong-inc/acl/overview/_index.md
app/_kong_plugins/acl/changelog.md:
  - app/_hub/kong-inc/acl/_changelog.md
app/_kong_plugins/forward-proxy/index.md:
  - app/_hub/kong-inc/forward-proxy/overview/_index.md
app/_kong_plugins/forward-proxy/changelog.md:
  - app/_hub/kong-inc/forward-proxy/_changelog.md
app/_kong_plugins/redirect/index.md:
  - app/_hub/kong-inc/redirect/overview/_index.md
app/_kong_plugins/redirect/changelog.md:
  - app/_hub/kong-inc/redirect/_changelog.md

# landing pages
app/_landing_pages/gateway/enterprise-vs-oss.yaml:
  - app/_src/gateway/index.md
  - app/_data/tables/features/gateway.yml
app/_landing_pages/gateway/rate-limiting.yaml:
  - app/_hub/kong-inc/rate-limiting/overview/_index.md
  - app/_hub/kong-inc/rate-limiting-advanced/overview/_index.md
app/_landing_pages/deck.yaml:
  - app/_src/deck/index.md
  - app/_src/deck/installation.md
  - app/_src/deck/faqs.md
app/_landing_pages/gateway.yaml:
  - app/_src/gateway/index.md
app/_landing_pages/gateway/secrets-management.yaml:
  - app/_src/gateway/kong-enterprise/secrets-management/index.md
  - app/_src/gateway/kong-enterprise/secrets-management/getting-started.md
  - app/_src/gateway/kong-enterprise/secrets-management/secrets-rotation.md
app/_landing_pages/gateway/authentication.yaml:
  - app/_src/gateway/kong-plugins/authentication/reference.md

# references 
app/deck/distributed-config.md:
  - app/_src/deck/guides/distributed-configuration.md
app/deck/environment-variables.md:
  - app/_src/deck/guides/environment-variables.md
app/deck/manage-deck-with-docker.md:
  - app/_src/deck/guides/run-with-docker-1.28.md
app/deck/object-defaults.md:
  - app/_src/deck/guides/defaults-v2.md
app/gateway/rate-limiting/strategies.md:
  - app/_hub/kong-inc/rate-limiting-advanced/overview/_index.md
  - app/_hub/kong-inc/rate-limiting/overview/_index.md
app/gateway/rate-limiting/window-types.md:
  - app/_hub/kong-inc/rate-limiting-advanced/overview/_index.md
  - app/_hub/kong-inc/rate-limiting/overview/_index.md
app/gateway/routing/index.md:
  - app/_src/gateway/key-concepts/routes/index.md
app/gateway/manage-kong-conf.md:
  - app/_src/gateway/production/kong-conf.md
app/gateway/logs.md:
  - app/_src/gateway/production/logging/log-reference.md
  - app/_src/gateway/production/logging/update-log-level-dynamically.md
  - app/_src/gateway/production/logging/ai-analytics.md
app/gateway/network-ports-firewall.md:
  - app/_src/gateway/production/networking/default-ports.md
  - app/_src/gateway/production/networking/firewall.md
app/gateway/cp-dp-communication.md:
  - app/_src/gateway/production/networking/cp-dp-proxy.md

# traffic control
app/gateway/traffic-control/proxy.md:
  - app/_src/gateway/how-kong-works/routing-traffic.md
  - app/_includes/md/admin-listen.md
app/gateway/routing/expressions.md:
  - app/_src/gateway/reference/expressions-language/index.md
  - app/_src/gateway/key-concepts/routes/expressions.md
  - app/_src/gateway/reference/expressions-language/language-references.md
  - app/_src/gateway/reference/expressions-language/performance.md
app/gateway/routing/expressions-router-examples.md:
  - app/_src/gateway/reference/expressions-language/index.md 
app/gateway/networking/dns-config-reference.md:
  - app/_src/gateway/production/networking/dns-considerations.md
app/gateway/traffic-control/health-checks-circuit-breakers.md:
  - /app/_src/gateway/how-kong-works/health-checks.md
app/gateway/traffic-control/load-balancing.md:
  - app/_src/gateway/how-kong-works/load-balancing.md

# policies
app/gateway/vulnerabilities.md:
  - app/_src/gateway/support/vulnerability-patching-process.md