# api pages
app/_api/gateway/admin-ee/_index.md:
 - app/_api/gateway/admin-ee/_index.md
app/_api/gateway/admin-oss/_index.md:
 - app/_api/gateway/admin-oss/_index.md
app/_api/gateway/dev-portal/_index.md:
 - app/_api/dev-portal/_index.md
app/_api/gateway/status/_index.md:
 - app/_api/gateway/status/_index.md
app/_api/konnect/api-products/_index.md:
 - app/_api/konnect/api-products/_index.md
app/_api/konnect/analytics-requests/_index.md:
 - app/_api/konnect/api-requests/_index.md
app/_api/konnect/application-auth-strategies/_index.md:
 - app/_api/konnect/application-auth-strategies/_index.md
app/_api/konnect/audit-logs/_index.md:
 - app/_api/konnect/audit-logs/_index.md
app/_api/konnect/cloud-gateways/_index.md:
 - app/_api/konnect/cloud-gateways/_index.md
app/_api/konnect/control-planes-config/_index.md:
 - app/_api/konnect/control-plane-configuration/_index.md
app/_api/konnect/control-planes/_index.md:
 - app/_api/konnect/control-planes/_index.md
app/_api/konnect/dev-portal/_index.md:
 - app/_api/konnect-portal/_index.md
app/_api/konnect/identity/_index.md:
 - app/_api/konnect/identity-management/_index.md
app/_api/konnect/mesh-control-planes/_index.md:
 - app/_api/konnect/mesh-manager/_index.md
app/_api/konnect/portal/_index.md:
 - app/_api/konnect/portal/_index.md
app/_api/konnect/portal-management/_index.md:
 - app/_api/konnect/portal-management/_index.md
app/_api/konnect/runtime-groups/_index.md:
 - app/_api/konnect/runtime-groups/_index.md
app/_api/konnect/ksearch/_index.md:
 - app/_api/konnect/search/_index.md

# how tos
app/_how-tos/dynamically-rewrite-simple-request-urls-with-routes.md:
  - app/_src/gateway/key-concepts/routes/index.md 

# traffic control
app/gateway/traffic-control/proxy.md:
  - app/_src/gateway/how-kong-works/routing-traffic.md
  - app/_includes/md/admin-listen.md

# entities
app/_gateway_entities/route.md:
  - app/_src/gateway/how-kong-works/routing-traffic.md
  - app/_src/gateway/key-concepts/routes/index.md
app/_gateway_entities/upstream.md:
  - app/_src/gateway/key-concepts/upstreams.md
