# Pages marked as won't do for which we don't have a page in the dev site
---
- docs_url: "/konnect/org-management/access-tokens/"
  dev_site_url: '/index/konnect-platform/'
  status: won't do
- docs_url: "/konnect/getting-started/app-registration/"
  dev_site_url: '/dev-portal/'
  status: won't do
- docs_url: "/contributing/community-expectations/"
  dev_site_url: '/'
  status: won't do
- docs_url: "/contributing/community/"
  dev_site_url: '/'
  status: won't do
- docs_url: "/contributing/conditional-rendering/"
  dev_site_url: '/'
  status: won't do
- docs_url: "/contributing/contribution-templates/"
  dev_site_url: '/'
  status: won't do
- docs_url: "/konnect/analytics/dashboard/"
  dev_site_url: '/advanced-analytics/'
  status: won't do
- docs_url: "/konnect/gateway-manager/declarative-config/"
  dev_site_url: '/konnect/gateway-manager/'
  status: won't do
- docs_url: "/contributing/diagrams/"
  dev_site_url: '/'
  status: won't do
- docs_url: "/konnect/api/errors/"
  dev_site_url: '/konnect-api/'
  status: won't do
- docs_url: "/konnect/api/filtering/"
  dev_site_url: '/konnect-api/'
  status: won't do
- docs_url: "/contributing/hackathons/"
  dev_site_url: '/'
  status: won't do
- docs_url: "/contributing/includes/"
  dev_site_url: '/'
  status: won't do
- docs_url: "/konnect/gateway-manager/data-plane-nodes/"
  dev_site_url: '/gateway-manager/data-plane-reference/'
  status: won't do
- docs_url: "/konnect/gateway-manager/plugins/"
  dev_site_url: '/gateway/entities/plugin/'
  status: won't do
- docs_url: "/contributing/"
  dev_site_url: '/'
  status: won't do
- docs_url: "/konnect/api-products/"
  dev_site_url: '/dev-portal/'
  status: won't do
- docs_url: "/contributing/kong-plugins/"
  dev_site_url: '/'
  status: won't do
- docs_url: "/konnect/analytics/use-cases/latency/"
  dev_site_url: '/advanced-analytics/'
  status: won't do
- docs_url: "/contributing/markdown-rules/"
  dev_site_url: '/'
  status: won't do
- docs_url: "/contributing/notices/"
  dev_site_url: '/'
  status: won't do
- docs_url: "/konnect/gateway-manager/data-plane-nodes/parameter-reference/"
  dev_site_url: '/gateway-manager/data-plane-reference/'
  status: won't do
- docs_url: "/contributing/partner-plugins/"
  dev_site_url: '/'
  status: won't do
- docs_url: "/konnect/api-products/productize-service/"
  dev_site_url: '/dev-portal/'
  status: won't do
- docs_url: "/gateway/latest/reference/rate-limiting/"
  dev_site_url: '/rate-limiting/'
  status: won't do
- docs_url: "/konnect/api-products/service-documentation/"
  dev_site_url: '/dev-portal/'
  status: won't do
- docs_url: "/konnect/org-management/sessions-reference/"
  dev_site_url: '/index/konnect-platform/'
  status: won't do
- docs_url: "/contributing/single-sourced-plugins/"
  dev_site_url: '/'
  status: won't do
- docs_url: "/contributing/single-sourced-versions/"
  dev_site_url: '/'
  status: won't do
- docs_url: "/contributing/style-guide/"
  dev_site_url: '/'
  status: won't do
- docs_url: "/konnect/org-management/system-accounts/"
  dev_site_url: '/index/konnect-platform/'
  status: won't do
- docs_url: "/konnect/analytics/use-cases/"
  dev_site_url: '/advanced-analytics/'
  status: won't do
- docs_url: "/contributing/user-interfaces/"
  dev_site_url: '/'
  status: won't do
- docs_url: "/konnect/org-management/users/"
  dev_site_url: '/index/konnect-platform/'
  status: won't do
- docs_url: "/contributing/variables/"
  dev_site_url: '/'
  status: won't do
- docs_url: "/contributing/word-choice/"
  dev_site_url: '/'
  status: won't do
- docs_url: "/gateway/latest/production/monitoring/"
  dev_site_url: '/gateway/logs/'
  status: won't do
- docs_url: "/gateway/latest/production/canary/"
  dev_site_url: '/plugins/canary/'
  status: won't do
- docs_url: "/gateway/latest/migrate-cassandra-to-postgres/"
  dev_site_url: '/gateway/'
  status: won't do
- docs_url: "/gateway/latest/kong-manager/get-started/services-and-routes/"
  dev_site_url: '/gateway/kong-manager/'
  status: won't do
- docs_url: "/gateway/latest/kong-manager/get-started/rate-limiting/"
  dev_site_url: '/gateway/kong-manager/'
  status: won't do
- docs_url: "/gateway/latest/kong-manager/get-started/proxy-caching/"
  dev_site_url: '/gateway/kong-manager/'
  status: won't do
- docs_url: "/gateway/latest/kong-manager/get-started/consumers/"
  dev_site_url: '/gateway/kong-manager/'
  status: won't do
- docs_url: "/gateway/latest/kong-manager/get-started/load-balancing/"
  dev_site_url: '/gateway/kong-manager/'
  status: won't do
- docs_url: "/gateway/latest/kong-manager/consumer-groups/"
  dev_site_url: '/gateway/kong-manager/'
  status: won't do
- docs_url: "/gateway/latest/plugin-development/wasm/filter-development-guide/"
  dev_site_url: '/gateway/configuration/'
  status: won't do
- docs_url: "/gateway/latest/plugin-development/wasm/filter-configuration/"
  dev_site_url: '/gateway/configuration/'
  status: won't do
- docs_url: "/gateway/latest/reference/wasm/"
  dev_site_url: '/gateway/configuration/'
  status: won't do
- docs_url: "/mesh/latest/introduction/how-kong-mesh-works/"
  dev_site_url: '/mesh/'
  status: won't do
- docs_url: "/mesh/latest/production/"
  dev_site_url: '/index/mesh/'
  status: won't do
- docs_url: "/mesh/latest/production/cp-deployment/single-zone/"
  dev_site_url: '/mesh/zone-proxy-auth/'
  status: won't do
- docs_url: "/mesh/latest/production/cp-deployment/multi-zone/"
  dev_site_url: '/mesh/multi-zone-authentication/'
  status: won't do
- docs_url: "/mesh/latest/production/cp-deployment/kubernetes/"
  dev_site_url: '/mesh/production-usage-values/'
  status: won't do
- docs_url: "/mesh/latest/policies/mutual-tls/"
  dev_site_url: '/mesh/policies/meshtls/'
  status: won't do
- docs_url: "/mesh/latest/policies/external-services/"
  dev_site_url: '/mesh/meshexternalservice/'
  status: won't do
- docs_url: "/mesh/latest/policies/service-health-probes/"
  dev_site_url: '/mesh/policies/meshhealthcheck/'
  status: won't do
- docs_url: "/mesh/latest/policies/protocol-support-in-kong-mesh/"
  dev_site_url: '/mesh/policies/'
  status: won't do
- docs_url: "/mesh/latest/networking/non-mesh-traffic/"
  dev_site_url: '/mesh/policies/meshtrafficpermission/'
  status: won't do
- docs_url: "/mesh/latest/policies/general-notes-about-kong-mesh-policies/"
  dev_site_url: '/mesh/policies/'
  status: won't do
- docs_url: "/mesh/latest/policies/how-kong-mesh-chooses-the-right-policy-to-apply/"
  dev_site_url: '/mesh/policies/'
  status: won't do
- docs_url: "/mesh/latest/policies/traffic-permissions/"
  dev_site_url: '/mesh/policies/meshtrafficpermission/'
  status: won't do
- docs_url: "/mesh/latest/policies/traffic-route/"
  dev_site_url: '/mesh/migration-to-the-new-policies/'
  status: won't do
- docs_url: "/mesh/latest/policies/traffic-metrics/"
  dev_site_url: '/mesh/policies/meshmetric/'
  status: won't do
- docs_url: "/mesh/latest/policies/traffic-trace/"
  dev_site_url: '/mesh/policies/meshtrace/'
  status: won't do
- docs_url: "/mesh/latest/policies/traffic-log/"
  dev_site_url: '/mesh/policies/meshaccesslog/'
  status: won't do
- docs_url: "/mesh/latest/policies/locality-aware/"
  dev_site_url: '/mesh/policies/meshloadbalancingstrategy/'
  status: won't do
- docs_url: "/mesh/latest/policies/fault-injection/"
  dev_site_url: '/mesh/policies/meshfaultinjection/'
  status: won't do
- docs_url: "/mesh/latest/policies/health-check/"
  dev_site_url: '/mesh/policies/meshhealthcheck/'
  status: won't do
- docs_url: "/mesh/latest/policies/circuit-breaker/"
  dev_site_url: '/mesh/policies/meshcircuitbreaker/'
  status: won't do
- docs_url: "/mesh/latest/policies/retry/"
  dev_site_url: '/mesh/policies/meshretry/'
  status: won't do
- docs_url: "/mesh/latest/policies/timeout/"
  dev_site_url: '/mesh/policies/meshtimeout/'
  status: won't do
- docs_url: "/mesh/latest/policies/rate-limit/"
  dev_site_url: '/mesh/policies/meshratelimit/'
  status: won't do
- docs_url: "/mesh/latest/policies/virtual-outbound/"
  dev_site_url: '/mesh/meshservice/'
  status: won't do
- docs_url: "/mesh/latest/policies/meshgatewayroute/"
  dev_site_url: '/mesh/policies/meshtcproute/'
  status: won't do
- docs_url: "/mesh/latest/features/opa/"
  dev_site_url: '/mesh/policies/meshopa/'
  status: won't do
- docs_url: "/mesh/latest/features/windows/"
  dev_site_url: '/mesh/'
  status: won't do
- docs_url: "/mesh/latest/reference/http-api/"
  dev_site_url: '/mesh/kubernetes-gateway-api/'
  status: won't do
- docs_url: "/mesh/latest/reference/proxy-template/"
  dev_site_url: '/mesh/'
  status: won't do
- docs_url: "/hub/kong-inc/application-registration/"
  dev_site_url: '/dev-portal/'
  status: won't do
- docs_url: "/hub/kong-inc/application-registration/configuration/"
  dev_site_url: '/dev-portal/'
  status: won't do
- docs_url: "/hub/kong-inc/application-registration/how-to/basic-example/"
  dev_site_url: '/dev-portal/'
  status: won't do
- docs_url: "/hub/kong-inc/application-registration/how-to/"
  dev_site_url: '/dev-portal/'
  status: won't do
- docs_url: "/hub/okta/okta/"
  dev_site_url: '/konnect-platform/sso/'
  status: won't do
- docs_url: "/gateway/api/admin-oss/latest/"
  dev_site_url: '/api/'
  status: won't do
