title: 'Some dummy title'
description: 'some dummy description for now'

weight: 900

config:
  second: 5
  hour: 1000
  policy: local


tools:
  - deck
  - admin-api
  - konnect-api
  - kic
  - terraform
