# frozen_string_literal: true

require 'active_support'
require 'active_support/core_ext/object/deep_dup'

module Jekyll
  module ReferencePages
    module AutoGenerated
      class Canonical < Jekyll::Page # rubocop:disable Style/Documentation
        def initialize(jekyll_page) # rubocop:disable Lint/MissingSuper,Metrics/MethodLength
          @site = jekyll_page.site

          process('index.md')

          @dir = jekyll_page.data.fetch('base_url')

          @content = jekyll_page.content.deep_dup

          @data = jekyll_page.data.deep_dup.merge(
            'canonical_url' => jekyll_page.data.fetch('base_url'),
            'canonical?' => true
          )
          @data.delete('seo_noindex')

          @url = jekyll_page.data.fetch('base_url')

          @relative_path = jekyll_page.relative_path
        end
      end
    end
  end
end
