# frozen_string_literal: true

require 'active_support'
require 'active_support/core_ext/object/deep_dup'

module Jekyll
  module ReferencePages
    module AutoGenerated
      class Page # rubocop:disable Style/Documentation
        include Jekyll::SiteAccessor

        def initialize(doc)
          @doc = doc
        end

        def dir
          @dir ||= url
        end

        def url
          @url ||= "#{base_url}#{page_release}/"
        end

        def data
          @data ||= @doc
                    .data
                    .deep_dup
                    .merge!(
                      'base_url' => base_url,
                      'latest?' => page_release == latest_available_release,
                      'release' => page_release,
                      'seo_noindex' => true,
                      'versioned' => true
                    ).merge!(metadata)
        end

        def relative_path
          @relative_path ||= @doc.relative_path
        end

        def content
          @content ||= @doc.content.deep_dup
        end

        def to_jekyll_page
          CustomJekyllPage.new(site: @doc.site, page: self)
        end

        private

        def metadata
          @metadata ||= site.config.dig('reference_metadata', *key)
        end

        def releases
          @releases ||= (site.data.dig('products', product, 'releases') || []).map do |r|
            Drops::Release.new(r)
          end.reject(&:label?)
        end

        def base_url
          @base_url ||= @doc.url.gsub(%r{/\d+\.\d+/}, '/').gsub('index/', '')
        end

        def page_release
          @page_release ||= releases.detect do |r|
            r['release'] == release_from_url
          end
        end

        def latest_available_release
          @latest_available_release ||= releases.detect(&:latest?)
        end

        def release_from_url
          @release_from_url ||= @doc.url[/\d+\.\d+/]
        end

        def product
          @product ||= metadata['products'].first
        end

        def key
          @key ||= @doc.url.split('/').reject(&:empty?).take_while { |s| s != 'reference' && !s.match?(/\d+\.\d+/) }
        end
      end
    end
  end
end
