name: Run site
description: Build and serve the site
runs:
  using: composite
  steps:
    - name: Build site
      shell: bash
      env:
        ENABLE_ALGOLIA: 0
        LC_CTYPE: en_US.UTF-8
        LANG: C.UTF-8
        NODE_OPTIONS: "--max_old_space_size=8192"
      run: exe/build

    - name: Serve site
      shell: bash
      run: |
        npx netlify dev --dir dist --offline --internal-disable-edge-functions --functions /tmp/no-functions & npx wait-on http://localhost:8888
