title: "AI GCP Model Armor configuration"
description: "Configuration for enforcing content safety policies on LLM requests and responses using GCP Model Armor."

weight: 900

variables:
  gcp_service_account_json:
    description: GCP service account credentials in JSON format
    value: $GCP_SERVICE_ACCOUNT_JSON
  project_id:
    description: GCP project identifier
    value: $GCP_PROJECT_ID
  location_id:
    description: GCP location identifier
    value: $GCP_LOCATION_ID
  template_id:
    description: Guardrail template identifier
    value: $GCP_TEMPLATE_ID

config:
  project_id: ${project_id}
  location_id: ${location_id}
  template_id: ${template_id}
  guarding_mode: "BOTH"
  gcp_use_service_account: true
  gcp_service_account_json: ${gcp_service_account_json}
  reveal_failure_categories: true
  request_failure_message: "Your request was blocked by content policies."
  response_failure_message: "The model's response was filtered for safety."
  timeout: 15000
  response_buffer_size: 4096
  text_source: "last_message"


tools:
  - deck
  - admin-api
  - konnect-api
  - kic
  - terraform
