metadata:
  products:
    - mesh
  content_type: 'reference'
  layout: 'reference'
  edition: 'mesh'
  plugin_schema: true
  breadcrumbs:
    - /mesh/

links:
  '/install/?': '/mesh/#install-kong-mesh'
  '/enterprise/?': '/mesh/'
  '/community/?': 'https://konghq.com/community'
  '/policies/?': '/mesh/policies/'
  '/features/?': '/mesh/enterprise/'

pages:
# Must for GA    
  -
    path: app/_src/guides/otel-metrics.md
    title: 'Collect metrics with OpenTelemetry'
    description: 'Collect and export metrics from {{site.mesh_product_name}} with OpenTelemetry and visualize them using Prometheus and Grafana.'
    url: '/mesh/collect-metrics-with-opentelemetry/'
    related_resources:
      - text: Mesh observability
        url: '/mesh/observability/'
      - text: Policy Hub
        url: /mesh/policies/
      - text: Service meshes
        url: /mesh/service-mesh/
    min_version:
      mesh: '2.7'
  -
    path: app/_src/introduction/concepts.md
    title: 'Concepts'
    description: 'Understand the core concepts of {{ site.mesh_product_name }}, including the Control Plane, Data Plane proxies, inbounds and outbounds, and resources like policies.'
    url: '/mesh/concepts/'
    related_resources:
      - text: Service meshes
        url: '/mesh/service-mesh/'
      - text: Mesh Policies
        url: '/mesh/policies-introduction/'
      - text: Mesh architecture
        url: /mesh/architecture/
      - text: Install Kong Mesh
        url: /mesh/#install-kong-mesh
    min_version:
      mesh: '2.7'
  -
    path: app/_src/networking/dns.md
    title: 'DNS'
    description: 'Learn how {{site.mesh_product_name}} DNS works with virtual IPs and service naming to enable transparent proxying.'
    url: '/mesh/dns/'
    related_resources:
      - text: Configure the Kong Mesh CNI
        url: '/mesh/cni/'
      - text: Transparent proxying
        url: '/mesh/transparent-proxying/'
      - text: Kubernetes annotations and labels
        url: /mesh/annotations/
      - text: Mesh concepts
        url: /mesh/concepts/
      - text: Service discovery
        url: /mesh/service-discovery/

# Post GA
  -
    path: app/_src/explore/observability.md
    title: 'Observability'
    description: 'Learn how to configure observability in {{site.mesh_product_name}} using Prometheus, Grafana, Jaeger, Loki, and Datadog.'
    url: '/mesh/observability/'
    related_resources:
      - text: Audit logs
        url: /mesh/access-audit/
      - text: '{{site.mesh_product_name}} resource sizing guidelines'
        url: '/mesh/resource-sizing-guidelines/'
      - text: '{{site.mesh_product_name}} validated versions'
        url: '/mesh/validated-versions/'
      - text: Policy Hub
        url: /mesh/policies/
      - text: Mesh CLI
        url: /mesh/cli/
      - text: Data plane health
        url: /mesh/dataplane-health/
  -
    path: app/_src/guides/meshidentity-spire-guide.md
    title: 'Issue identity with MeshIdentity Spire provider'
    description: 'Learn how to issue identities using Spire provider and how to use them to encrypt traffic in mesh.'
    url: '/mesh/meshidentity-spire/'
    related_resources:
      - text: Data plane proxy
        url: '/mesh/data-plane-proxy/'
    tags:
      - security
    min_version:
      mesh: '2.12'
