metadata:
  products:
    - mesh
  content_type: 'reference'
  layout: 'reference'
  edition: 'mesh'
  plugin_schema: true
  breadcrumbs:
    - /mesh/

links:
  '/install/?': '/mesh/#install-kong-mesh'
  '/enterprise/?': '/mesh/'
  '/community/?': 'https://konghq.com/community'
  '/policies/?': '/mesh/policies/'
  '/features/?': '/mesh/enterprise/'

pages:
# Must for GA    
  -
    path: app/_src/guides/otel-metrics.md
    title: 'Collect metrics with OpenTelemetry'
    description: 'Collect and export metrics from {{site.mesh_product_name}} with OpenTelemetry and visualize them using Prometheus and Grafana.'
    url: '/mesh/collect-metrics-with-opentelemetry/'
    related_resources:
      - text: Mesh observability
        url: '/mesh/observability/'
      - text: Policy Hub
        url: /mesh/policies/
      - text: Service meshes
        url: /mesh/service-mesh/
    min_version:
      mesh: '2.7'
