url_origin:
  konnect: $KONNECT_PROXY_URL
  on_prem: http://localhost:8000

container:
  konnect: $KONNECT_DP_CONTAINER
  on_prem: kong-quickstart-gateway

validations:
  - id: rate-limit-check
    message: API rate limit exceeded
    status_code: 429

  - id: unauthorized-check
    message: Unauthorized
    status_code: 401

  - id: request
    status_code: 200

  - id: kubernetes-resource