metadata:
  title: Kong on-prem deployment topologies
  content_type: landing_page
  description: This page lists the different {{site.base_gateway}} deployment topologies.
  breadcrumbs:
    - /gateway/