name: Run Publish Tests Report
description: Publishes tests report to github
runs:
  using: "composite"
  steps:
    - name: Publish Test Report
      uses: ctrf-io/github-test-reporter@e500b992f936420eb633c91644cf10d4d71df700 # v1
      with:
        report-path: './tools/automated-tests/testReport.json'
        summary-report: true
        test-report: true
        failed-folded-report: true
        skipped-report: true
        report-order: 'summary-report,test-report,failed-folded-report,skipped-report'