name: Run Publish Tests Report
description: Publishes tests report to github
runs:
  using: "composite"
  steps:
    - name: Publish Test Report
      uses: ctrf-io/github-test-reporter@7974087018bf4857cf5a9d78723e152038c3fa31 # v1
      with:
        report-path: './tools/automated-tests/testReport.json'
        summary-report: true
        test-report: true
        failed-folded-report: true
        skipped-report: true
        report-order: 'summary-report,test-report,failed-folded-report,skipped-report'