title: KIC Index File
sections:
  - title: Some KIC Pages
    items:
      - path: /kubernetes-ingress-controller/**/*
    auto_exclude: true
  - title: Routing
    items:
      - path: /kubernetes-ingress-controller/routing/http/
      - path: /kubernetes-ingress-controller/routing/grpc/
      - path: /kubernetes-ingress-controller/routing/grpc-over-http/