# frozen_string_literal: true

require_relative '../lib/ordered_generator'

module Jekyll
  class ReferencePagesGenerator < OrderedGenerator # rubocop:disable Style/Documentation
    def generate(site)
      ReferencePages::AutoGenerated::Generator.run(site)
      ReferencePages::Generator.run(site)
    end
  end
end
