# frozen_string_literal: true

module Jekyll
  class ReferencePagesGenerator < Generator # rubocop:disable Style/Documentation
    priority :normal

    def generate(site)
      ReferencePages::AutoGenerated::Generator.run(site)
      ReferencePages::Generator.run(site)
    end
  end
end
