# frozen_string_literal: true

module Jekyll
  class ReferencePagesGenerator < Generator # rubocop:disable Style/Documentation
    priority :normal

    def generate(site)
      ReferencePages::AutoGenerated::Generator.run(site)

      reference_sources = collect_reference_source_mtimes(site)

      if Utils::Incremental.enabled? && @cached_ref_mtimes && @cached_ref_pages && !Utils::Incremental.mtimes_changed?(reference_sources, @cached_ref_mtimes)
        site.pages.concat(@cached_ref_pages)
        Utils::Incremental.skip_regeneration(site, @cached_ref_pages)
        Jekyll.logger.info 'IncrementalGen:', 'Skipped ReferencePages::Generator (sources unchanged)'
        return
      end

      before = site.pages.size
      ReferencePages::Generator.run(site)

      @cached_ref_pages = site.pages[before..]
      @cached_ref_mtimes = reference_sources
    end

    private

    def collect_reference_source_mtimes(site)
      mtimes = {}
      (site.pages + site.documents).each do |page|
        next if page.data['content_type'] != 'reference'
        next if page.data['auto_generated']

        source_path = page.respond_to?(:path) ? page.path : site.in_source_dir(page.relative_path)
        mtimes[source_path] = File.mtime(source_path) if File.exist?(source_path)
      end
      mtimes
    end
  end
end
