title: 'Simple outbound TCP configuration'
description: 'This configuration will be applied to all data plane proxies inside of Mesh.'

weight: 900

namespace: kuma-demo

config:
  type: MeshTimeout
  name: tcp-timeout
  mesh: default
  spec:
    to:
      - targetRef:
          kind: Mesh
        default:
          idleTimeout: 20s
          connectionTimeout: 2s