name: Scheduled Broken Links Checker
on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * 0'

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

env:
  VITE_PORTAL_API_URL: ${{ vars.VITE_PORTAL_API_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: 'recursive'

      - name: Install deps
        uses: './.github/reusable-steps/install-deps'

      - name: Run site
        uses: './.github/reusable-steps/run-site'
        
      - name: Run link checker
        run: |
          cd tools/broken-link-checker
          npm ci
          node full.js --host http://localhost:8888
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

      - name: Notify Slack
        if: ${{ !cancelled() }}
        uses: './.github/reusable-steps/notify-slack'
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status }}
